"""Initial schema

Revision ID: d4f5af1c8b0e
Revises: 
Create Date: 2026-02-23 20:40:46.788291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f5af1c8b0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ebay_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=120), nullable=True),
    sa.Column('ebay_username', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ebay_stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ebay_stores_user_id'), ['user_id'], unique=False)

    op.create_table('supplier_vaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_vaults', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_vaults_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ebay_store_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_sku', sa.String(length=120), nullable=True),
    sa.Column('ebay_item_id', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('source_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ebay_store_id'], ['ebay_stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_ebay_store_id'), ['ebay_store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ebay_order_id', sa.String(length=120), nullable=False),
    sa.Column('buyer_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='detected', nullable=False),
    sa.Column('total_paid_by_buyer', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_supplier_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_ebay_order_id'), ['ebay_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_product_id'))
        batch_op.drop_index(batch_op.f('ix_orders_ebay_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_products_ebay_store_id'))

    op.drop_table('products')
    with op.batch_alter_table('supplier_vaults', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_vaults_user_id'))

    op.drop_table('supplier_vaults')
    with op.batch_alter_table('ebay_stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ebay_stores_user_id'))

    op.drop_table('ebay_stores')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
